
language: node_js
node_js:
  - "8"
cache:
  directories:
    - ~/.npm
    - node_modules
install:
  - npm install
  - npm install cypress
script:
  - $(npm bin)/cypress run --record --key 086ddcbe-23be-444e-a68f-3aa68e957740
